### ISSUE TITLE
sql 쿼리 로그 설정 & 프론트 테스트용 배포 준비(회원가입, 로그인)

### ISSUE THREAD

**Issue by Moveuk** [Inssagram-CloneCode/backend_server#5]
show_sql의 설정 방식이 변경되어 쿼리가 나오지 않았음.
변경 후 처럼 yml을 바꿔주면 로그가 찍힘

 기존
```
  jpa:
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: update
```

변경
```
 jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
```

![Image](https://user-images.githubusercontent.com/84966961/185792939-6588f64a-6bb5-4257-941b-13340eee3078.png)
